### ISSUE TITLE
Unable to turn it on

### ISSUE THREAD

**Issue by maciejfikus** [juliangut/zf-maintenance#7]
Hey, I've installed your module via composer so the files went to vendor dir. However, I'am unable to use it in any way. 

Even though there is "'Jgut\Zf\Maintenance'" in application.config.php it is ignoring the zf-maintenance.global.php which is also in this dir - config. 

I can put whatever content in maintenance.global.php I want - it does pretty much nothing. 

How am I supposed to turn on the maintenance mode then?

// edit.
Turns out I am just a noob. Although this point:
3.Copy config\zf-maintenance.global.php.dist to your config directory and rename it zf-maintenance.global.php

is wrong which may be misleading for zend begginers. This file should land in config/autoload dir, not just config. 

Cheers.

**Comment by juliangut** [comment]
Good to know you were able to find the problem.
